syntax = "proto3";

package books;

option go_package = "mkode.books.v1;booksv1";

//Storing books and getting them
service Books {
    //Add book to storage
    rpc AddBook(AddBookRequest) returns (AddBookResponse);
    //Add new course book to storage
    rpc AddCourseBook(AddCourseBookRequest) returns (AddCourseBookResponse);
    //Take some copies of the book from the storage
    rpc TakeBook(TakeBookRequest) returns (TakeBookResponse);
    //Get book by it's id (uuid)
    rpc GetBookByID(GetBookByIDRequest) returns (GetBookByIDResponse);
    //Get book by it's title
    rpc GetBookByTitle(GetBookByTitleRequest) returns (GetBookByTitleResponse);
    //Get course book by it's title, grade and author
    rpc GetCourseBookByTitle(GetCourseBookByTitleRequest) returns (GetCourseBookByTitleResponse);
    //Get list of course books by subject and grade
    rpc GetListOfCourseBooksBySubjectAndGrade(GetListOfCourseBooksBySubjectAndGradeRequest) returns (GetListOfCourseBooksBySubjectAndGradeResponse);
    //Delete book by it's id
    rpc DeleteBook(DeleteBookRequest) returns (DeleteBookResponse);
    //Add some copies to the existing book
    rpc AddCopies(AddCopiesRequest) returns (AddCopiesResponse);
    //Get list of all books in the store
    rpc GetListOfBooks(GetListOfBooksRequest) returns (GetListOfBooksResponse);
    //Get filtered list of books from the storage
    rpc FilterBooksByGenreList(FilterBooksByGenreListRequest) returns (FilterBooksByGenreListResponse);
}

//-----Add Book-----//
message AddBookRequest {
    string genre = 1;
    string title = 2;
    string author = 3;
    int64 quantity = 4;
}
message AddBookResponse {
    string book_id = 1;
}
//-----Add Book-----//


//-----Add Course Book-----//
message AddCourseBookRequest {
    string subject = 1;
    string title = 2;
    string author = 3;
    int32 grade = 4;
    int64 quantity = 5;
}

message AddCourseBookResponse {
    string book_id = 1;
}
//-----Add Course Book-----//



//-----Take Book-----//
message TakeBookRequest {
    string book_id = 1;
    int64 take_copies = 2;
}
message TakeBookResponse {
    bool success = 1;
}
//-----Take Book-----//



//-----Get Book By Ttile-----//
message GetBookByTitleRequest {
    string title = 1;
}
message GetBookByTitleResponse {
    Book book = 1;
}
//-----Get Book By Ttile-----//



//-----Get Course Book By Title-----//
message GetCourseBookByTitleRequest {
    string subject = 1;
    string title = 2;
    string author = 3;
    int32 grade = 4;
}

message GetCourseBookByTitleResponse {
    CourseBook book = 1;
}
//-----Get Course Book By Title-----//


//-----Get Book By ID-----//
message GetBookByIDRequest {
    string book_id = 1;
}
message GetBookByIDResponse {
    Book book = 1;
}
//-----Get Book By ID-----//



message GetListOfCourseBooksBySubjectAndGradeRequest {
    string subject = 1;
    int32 grade = 2;
}

message GetListOfCourseBooksBySubjectAndGradeResponse {
    repeated CourseBook books = 1;
}



//-----Delete Book-----//
message DeleteBookRequest {
    string book_id = 1;
}
message DeleteBookResponse {
    bool success = 1;
}
//-----Delete Book-----//


//-----Add Copies-----//
message AddCopiesRequest {
    string book_id = 1;
    int64 copies_to_add = 2;
}
message AddCopiesResponse {
    bool success = 1;
}
//-----Add Copies-----//



//-----Get List Of Books-----//
message GetListOfBooksRequest {}
message GetListOfBooksResponse {
    repeated Book books = 1;
}
//-----Get List Of Books-----//



//-----Filter Books By Genre-----//
message FilterBooksByGenreListRequest {
    string genre = 1;
}
message FilterBooksByGenreListResponse {
    repeated Book filtered_books = 1;
}
//-----Filter Books By Genre-----//



//-----Book-----//
message Book {
    string title = 1;
    string genre = 2;
    string author = 3;
    int64 available_copies = 4;
    string id = 5;
}
//-----Book-----//

//-----Course Book-----//
message CourseBook {
    string title = 1;
    string subject = 2;
    string author = 3;
    int32 grade = 4;
    int64 available_copies = 5;
    string id = 6;
}
//-----Course Book-----//

