syntax = "proto3";

package issue;

option go_package = "mkode.issue.v1;issuev1";

import "google/protobuf/timestamp.proto";

//Issue books, return them, report loss and viewing debtors
service IssueService {
  //Issue book by it's id and student's id for the fixed amount of days
  rpc IssueBook (IssueRequest) returns (IssueResponse) {}
  //Check the availability of the book to be issued
  rpc CheckAvailability (CheckAvailabilityRequest) returns (CheckAvailabilityResponse) {}
  //Return book after issuing it
  rpc ReturnBook (ReturnRequest) returns (ReturnResponse) {}
  //Report loss of the book
  rpc ReportLost (ReportLostRequest) returns (ReportLostResponse) {}
  //Get all the saved debts 
  rpc GetAllDebts (GetAllDebtsRequest) returns (GetAllDebtsResponse) {}
  //View all the saved debtors 
  rpc ViewDebtors (ViewDebtorsRequest) returns (ViewDebtorsResponse) {}
  //Take a book from the storage of books service
  rpc AddBook (AddBookRequest) returns (AddBookResponse) {}
}

message IssueRequest {
  string book_id = 1;
  string student_id = 2;
  int32 days_due = 3; // optional, default 14
}

message IssueResponse {
  string issue_id = 1;
}

message CheckAvailabilityRequest {
  string book_id = 1;
}

message CheckAvailabilityResponse {
  int32 available_copies = 1;
  int32 total_copies = 2;
}

message ReturnRequest {
  string issue_id = 1;
}

message ReturnResponse {
  int32 fine = 1;
}

message ReportLostRequest {
  string issue_id = 1;
}

message ReportLostResponse {
  int32 fine = 1;
}

message GetAllDebtsRequest {}

message GetAllDebtsResponse {
  repeated Debt debts = 1;
}

message ViewDebtorsRequest {
  int32 limit = 1; // optional
}

message ViewDebtorsResponse {
  repeated Debt debts = 1;
  bool from_cache = 2;
}

message Debt {
  string issue_id = 1;
  string student_id = 2;
  string student_name = 3;
  string book_id = 4;
  string book_title = 5;
  google.protobuf.Timestamp due_date = 6;
  int32 overdue_days = 7;
  int32 fine = 8;
}

message AddBookRequest {
  string title = 1;
  int32 total_copies = 2;
}

message AddBookResponse {
  string book_id = 1;
}
