syntax = "proto3";

package booking;

option go_package = "mkode.booking.v1;bookingv1";

service Book {
    rpc Book (BookRequest) returns (BookResponse);
    rpc CancelBooking (CancelBookingRequest) returns (CancelBookingResponse);
}

message BookRequest {
    string email = 1;
    string boxName = 2;
    int64 peopleAmount = 3;
    string timeStart = 4;
    int64 timeHrs = 5;
    int64 timeMins = 6;
}

message BookResponse {
    bool success = 1;
    int64 reserve_id = 2;
    int64 balance = 3;
}

message CancelBookingRequest {
    int64 booking_id = 1;
    string email = 2;
}

message CancelBookingResponse {
    bool success = 1;
    int64 refunded_amount = 2;
    int64 balance = 3;
}